version: '3'

services:
  swagger-ui-watcher:
    build: swagger-ui-watcher/build
    image: swagger-ui-watcher
    container_name: swagger-ui-watcher
    ports:
      - 8000:8000
    volumes:
      - ./swagger:/swagger
    command: /swagger/swagger.yaml

  # apisprout:
  #   image: danielgtaylor/apisprout
  #   container_name: apisprout
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./swagger/swagger.yaml:/swagger.yaml
  #   command: /swagger.yaml --watch

  swagger-api:
    image: stoplight/prism:3
    container_name: 'swagger-api'
    ports:
      - 4010:4010
    command: mock -h 0.0.0.0 /swagger.yaml
    volumes:
      - ./swagger/swagger.yaml:/swagger.yaml
